# DevCrew Installer Script for Windows
#
# Install from GitHub (Global):
#   Invoke-Expression (Invoke-WebRequest -Uri "https://raw.githubusercontent.com/charlesmu99/devcrew/main/install.ps1").Content
#
# Install from Gitee (China):
#   Invoke-Expression (Invoke-WebRequest -Uri "https://gitee.com/amutek/devcrew/raw/main/install.ps1").Content

param(
    [string]$TargetDir = ".",
    [string]$Mirror = "github"  # Options: github, gitee
)

$ErrorActionPreference = "Stop"

# Configuration - Select mirror
if ($Mirror -eq "gitee") {
    # Try alternative Gitee API endpoint
    $RepoUrl = "https://gitee.com/amutek/devcrew/archive/main.zip"
} else {
    $RepoUrl = "https://github.com/charlesmu99/devcrew/archive/refs/heads/main.zip"
}

$TempDir = [System.IO.Path]::GetTempPath() + [System.Guid]::NewGuid().ToString()

# Colors for output
function Write-Info($message) {
    Write-Host "[INFO] $message" -ForegroundColor Cyan
}

function Write-Success($message) {
    Write-Host "[SUCCESS] $message" -ForegroundColor Green
}

function Write-Warning($message) {
    Write-Host "[WARNING] $message" -ForegroundColor Yellow
}

function Write-Error($message) {
    Write-Host "[ERROR] $message" -ForegroundColor Red
}

# Cleanup function
function Cleanup {
    if (Test-Path $TempDir) {
        Remove-Item -Recurse -Force $TempDir -ErrorAction SilentlyContinue
    }
}

# Check if DevCrew is already installed
# Note: .qoder directory is auto-generated by Qoder IDE, so we check for devcrew-specific content
function Check-QoderCompatibility {
    Write-Info "Checking Qoder compatibility..."
    
    $devcrewInstalled = $false
    $agentsPath = Join-Path $TargetDir ".qoder\agents"
    $skillsPath = Join-Path $TargetDir ".qoder\skills"
    $workspacePath = Join-Path $TargetDir ".devcrew-workspace"
    
    # Check for devcrew-prefixed agents
    if (Test-Path $agentsPath) {
        $devcrewAgents = Get-ChildItem -Path $agentsPath -Filter "devcrew-*.md" -ErrorAction SilentlyContinue
        if ($devcrewAgents) {
            $devcrewInstalled = $true
        }
    }
    
    # Check for devcrew-prefixed skills
    if (Test-Path $skillsPath) {
        $devcrewSkills = Get-ChildItem -Path $skillsPath -Directory -Filter "devcrew-*" -ErrorAction SilentlyContinue
        if ($devcrewSkills) {
            $devcrewInstalled = $true
        }
    }
    
    # Check for .devcrew-workspace
    if (Test-Path $workspacePath) {
        $devcrewInstalled = $true
    }
    
    if ($devcrewInstalled) {
        Write-Warning "DevCrew appears to be already installed in this directory."
        Write-Host ""
        $response = Read-Host "Do you want to update the existing installation? (y/N)"
        if ($response -notmatch '^[Yy]$') {
            Write-Info "Installation cancelled."
            exit 0
        }
        Write-Info "Proceeding with update..."
    }
}

# Download DevCrew
function Download-DevCrew {
    Write-Info "Downloading DevCrew..."
    
    $zipPath = Join-Path $TempDir "devcrew.zip"
    
    try {
        Invoke-WebRequest -Uri $RepoUrl -OutFile $zipPath -UseBasicParsing
        Write-Success "Download completed."
    }
    catch {
        Write-Error "Failed to download DevCrew. Please check your internet connection."
        exit 1
    }
    
    return $zipPath
}

# Extract and install
function Install-DevCrew($zipPath) {
    Write-Info "Extracting files..."
    
    Expand-Archive -Path $zipPath -DestinationPath $TempDir -Force
    
    # Debug: List contents of temp directory
    Write-Info "Temp directory contents:"
    Get-ChildItem -Path $TempDir | ForEach-Object { Write-Info "  - $($_.Name)" }
    
    $extractedDir = Get-ChildItem -Path $TempDir -Directory | Where-Object { $_.Name -like "devcrew*" } | Select-Object -First 1
    
    # Debug: List contents of extracted directory
    if ($extractedDir) {
        Write-Info "Extracted directory contents:"
        Get-ChildItem -Path $extractedDir.FullName | ForEach-Object { Write-Info "  - $($_.Name)" }
    }
    
    if (-not $extractedDir) {
        Write-Error "Could not find extracted DevCrew directory."
        exit 1
    }
    
    Write-Info "Found extracted directory: $($extractedDir.FullName)"
    
    Write-Info "Installing DevCrew to $TargetDir..."
    
    # Create target directory if it doesn't exist
    if (-not (Test-Path $TargetDir)) {
        New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
    }
    
    # Copy .qoder directory (incremental update)
    $qoderSource = Join-Path $extractedDir.FullName ".qoder"
    if (Test-Path $qoderSource) {
        $qoderTarget = Join-Path $TargetDir ".qoder"
        New-Item -ItemType Directory -Path $qoderTarget -Force | Out-Null
        
        # Copy agents (skip existing)
        $agentsSource = Join-Path $qoderSource "agents"
        if (Test-Path $agentsSource) {
            $agentsTarget = Join-Path $qoderTarget "agents"
            New-Item -ItemType Directory -Path $agentsTarget -Force | Out-Null
            Get-ChildItem -Path $agentsSource -Filter "*.md" | ForEach-Object {
                $agentTarget = Join-Path $agentsTarget $_.Name
                if (-not (Test-Path $agentTarget)) {
                    Copy-Item -Path $_.FullName -Destination $agentTarget
                    Write-Info "Added new agent: $($_.Name)"
                }
            }
        }
        
        # Copy skills (skip existing)
        $skillsSource = Join-Path $qoderSource "skills"
        if (Test-Path $skillsSource) {
            $skillsTarget = Join-Path $qoderTarget "skills"
            New-Item -ItemType Directory -Path $skillsTarget -Force | Out-Null
            Get-ChildItem -Path $skillsSource -Directory | ForEach-Object {
                $skillTarget = Join-Path $skillsTarget $_.Name
                if (-not (Test-Path $skillTarget)) {
                    Copy-Item -Recurse -Path $_.FullName -Destination $skillTarget
                    Write-Info "Added new skill: $($_.Name)"
                }
            }
        }
        
        Write-Success "Updated .qoder/ directory (incremental)."
    }
    
    # Copy .devcrew-workspace directory (incremental update)
    $workspaceSource = Join-Path $extractedDir.FullName ".devcrew-workspace"
    Write-Info "Looking for .devcrew-workspace at: $workspaceSource"
    
    if (Test-Path $workspaceSource) {
        Write-Info "Found .devcrew-workspace source directory"
        $workspaceTarget = Join-Path $TargetDir ".devcrew-workspace"
        New-Item -ItemType Directory -Path $workspaceTarget -Force | Out-Null
        
        # Only copy docs templates if not exist
        $docsSource = Join-Path $workspaceSource "docs"
        if (Test-Path $docsSource) {
            $docsTarget = Join-Path $workspaceTarget "docs"
            New-Item -ItemType Directory -Path $docsTarget -Force | Out-Null
            Get-ChildItem -Path $docsSource -Filter "*.md" | ForEach-Object {
                $docTarget = Join-Path $docsTarget $_.Name
                if (-not (Test-Path $docTarget)) {
                    Copy-Item -Path $_.FullName -Destination $docTarget
                    Write-Info "Added new doc: $($_.Name)"
                }
            }
        }
        
        # Create knowledge and projects directories if not exist
        $knowledgePath = Join-Path $workspaceTarget "knowledge"
        $projectsPath = Join-Path $workspaceTarget "projects"
        New-Item -ItemType Directory -Path $knowledgePath -Force | Out-Null
        New-Item -ItemType Directory -Path $projectsPath -Force | Out-Null
        
        Write-Success "Updated .devcrew-workspace/ directory (incremental)."
    } else {
        Write-Warning ".devcrew-workspace source directory not found in extracted archive"
    }
    
    # Copy README files
    Get-ChildItem -Path $extractedDir.FullName -Filter "README*.md" | ForEach-Object {
        Copy-Item -Path $_.FullName -Destination $TargetDir
    }
}

# Verify installation
function Verify-Installation {
    Write-Info "Verifying installation..."
    
    $errors = 0
    
    $qoderPath = Join-Path $TargetDir ".qoder"
    $workspacePath = Join-Path $TargetDir ".devcrew-workspace"
    
    if (-not (Test-Path $qoderPath)) {
        Write-Error ".qoder/ directory not found after installation."
        $errors++
    }
    
    if (-not (Test-Path $workspacePath)) {
        Write-Error ".devcrew-workspace/ directory not found after installation."
        $errors++
    }
    
    if ($errors -eq 0) {
        Write-Success "Installation verified successfully!"
        return $true
    }
    else {
        return $false
    }
}

# Print next steps
function Print-NextSteps {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Success "DevCrew has been successfully installed!"
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:"
    Write-Host ""
    Write-Host "  1. Open your project in Qoder IDE"
    Write-Host "  2. Run the initialization Skill:"
    Write-Host "     'Run devcrew-knowledge-dispatch Skill to initialize the knowledge base'"
    Write-Host ""
    Write-Host "  3. Start using DevCrew with your first requirement!"
    Write-Host ""
    Write-Host "Documentation:"
    Write-Host "  - Agent Knowledge Map: .devcrew-workspace/docs/agent-knowledge-map.md"
    Write-Host "  - Project Introduction: README.md"
    Write-Host ""
    Write-Host "To uninstall:"
    Write-Host "  Remove-Item -Recurse -Force .qoder, .devcrew-workspace"
    Write-Host ""
}

# Main function
function Main {
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "  DevCrew Installer for Qoder" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
    
    # Check OS
    $os = [System.Environment]::OSVersion.Platform
    Write-Info "Detected: Windows"
    
    # Create temp directory
    New-Item -ItemType Directory -Path $TempDir -Force | Out-Null
    
    $success = $false
    try {
        Check-QoderCompatibility
        $zipPath = Download-DevCrew
        Install-DevCrew $zipPath
        
        if (Verify-Installation) {
            Print-NextSteps
            $success = $true
        }
        else {
            Write-Error "Installation verification failed."
        }
    }
    catch {
        Write-Error "An error occurred during installation: $_"
    }
    finally {
        Cleanup
    }
    
    # Pause to keep window open
    Write-Host ""
    Write-Host "Press any key to continue..." -ForegroundColor Cyan
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    
    if (-not $success) {
        exit 1
    }
}

# Run main function
Main
