#!/bin/bash
# DevCrew Installer Script
# Supports macOS and Linux/WSL
# 
# Install from GitHub (Global):
#   curl -fsSL https://raw.githubusercontent.com/charlesmu99/devcrew/main/install.sh | bash
#
# Install from Gitee (China):
#   curl -fsSL https://gitee.com/amutek/devcrew/raw/main/install.sh | bash
#
# Install to specific directory:
#   curl -fsSL <url> | bash -s /path/to/project

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration - Auto-detect mirror based on script source
SCRIPT_SOURCE="${SCRIPT_SOURCE:-github}"

if [ "$SCRIPT_SOURCE" = "gitee" ]; then
    REPO_URL="https://gitee.com/amutek/devcrew/repository/archive/main.tar.gz"
else
    REPO_URL="https://github.com/charlesmu99/devcrew/archive/refs/heads/main.tar.gz"
fi

TEMP_DIR="$(mktemp -d)"
TARGET_DIR="${1:-.}"

# Cleanup on exit
trap "rm -rf $TEMP_DIR" EXIT

# Print functions
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if DevCrew is already installed
# Note: .qoder directory is auto-generated by Qoder IDE, so we check for devcrew-specific content
check_qoder_compatibility() {
    print_info "Checking Qoder compatibility..."
    
    local devcrew_installed=false
    
    # Check for devcrew-prefixed agents
    if [ -d "$TARGET_DIR/.qoder/agents" ]; then
        if ls "$TARGET_DIR/.qoder/agents"/devcrew-*.md 1> /dev/null 2>&1; then
            devcrew_installed=true
        fi
    fi
    
    # Check for devcrew-prefixed skills
    if [ -d "$TARGET_DIR/.qoder/skills" ]; then
        for skill_dir in "$TARGET_DIR/.qoder/skills"/devcrew-*; do
            if [ -d "$skill_dir" ]; then
                devcrew_installed=true
                break
            fi
        done
    fi
    
    # Check for devcrew-workspace
    if [ -d "$TARGET_DIR/devcrew-workspace" ]; then
        devcrew_installed=true
    fi
    
    if [ "$devcrew_installed" = true ]; then
        print_warning "DevCrew appears to be already installed in this directory."
        echo ""
        read -p "Do you want to update the existing installation? (y/N): " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_info "Installation cancelled."
            exit 0
        fi
        print_info "Proceeding with update..."
    fi
}

# Download DevCrew
download_devcrew() {
    print_info "Downloading DevCrew..."
    
    if command -v curl &> /dev/null; then
        curl -fsSL "$REPO_URL" -o "$TEMP_DIR/devcrew.tar.gz"
    elif command -v wget &> /dev/null; then
        wget -q "$REPO_URL" -O "$TEMP_DIR/devcrew.tar.gz"
    else
        print_error "Neither curl nor wget is installed. Please install one of them."
        exit 1
    fi
    
    print_success "Download completed."
}

# Extract and install
install_devcrew() {
    print_info "Extracting files..."
    tar -xzf "$TEMP_DIR/devcrew.tar.gz" -C "$TEMP_DIR"
    
    local extracted_dir="$TEMP_DIR/devcrew-main"
    
    # If the directory name is different, find it
    if [ ! -d "$extracted_dir" ]; then
        extracted_dir=$(find "$TEMP_DIR" -maxdepth 1 -type d -name "devcrew*" | head -n 1)
    fi
    
    print_info "Installing DevCrew to $TARGET_DIR..."
    
    # Create target directory if it doesn't exist
    mkdir -p "$TARGET_DIR"
    
    # Copy .qoder directory (incremental update)
    if [ -d "$extracted_dir/.qoder" ]; then
        mkdir -p "$TARGET_DIR/.qoder"
        
        # Copy agents (overwrite devcrew- prefixed, skip others)
        if [ -d "$extracted_dir/.qoder/agents" ]; then
            mkdir -p "$TARGET_DIR/.qoder/agents"
            for agent in "$extracted_dir/.qoder/agents"/*.md; do
                if [ -f "$agent" ]; then
                    agent_name=$(basename "$agent")
                    is_devcrew=false
                    case "$agent_name" in
                        devcrew-*) is_devcrew=true ;;
                    esac
                    if [ "$is_devcrew" = true ] || [ ! -f "$TARGET_DIR/.qoder/agents/$agent_name" ]; then
                        cp "$agent" "$TARGET_DIR/.qoder/agents/"
                        if [ -f "$TARGET_DIR/.qoder/agents/$agent_name" ] && [ "$is_devcrew" = true ]; then
                            print_info "Updated agent: $agent_name"
                        else
                            print_info "Added new agent: $agent_name"
                        fi
                    fi
                fi
            done
        fi
        
        # Copy skills (overwrite devcrew- prefixed, skip others)
        if [ -d "$extracted_dir/.qoder/skills" ]; then
            mkdir -p "$TARGET_DIR/.qoder/skills"
            for skill_dir in "$extracted_dir/.qoder/skills"/*; do
                if [ -d "$skill_dir" ]; then
                    skill_name=$(basename "$skill_dir")
                    is_devcrew=false
                    case "$skill_name" in
                        devcrew-*) is_devcrew=true ;;
                    esac
                    if [ "$is_devcrew" = true ] || [ ! -d "$TARGET_DIR/.qoder/skills/$skill_name" ]; then
                        if [ -d "$TARGET_DIR/.qoder/skills/$skill_name" ] && [ "$is_devcrew" = true ]; then
                            rm -rf "$TARGET_DIR/.qoder/skills/$skill_name"
                            print_info "Updated skill: $skill_name"
                        else
                            print_info "Added new skill: $skill_name"
                        fi
                        cp -r "$skill_dir" "$TARGET_DIR/.qoder/skills/"
                    fi
                fi
            done
        fi
        
        print_success "Updated .qoder/ directory (incremental)."
    fi
    
    # Copy devcrew-workspace directory (incremental update)
    mkdir -p "$TARGET_DIR/devcrew-workspace"
    
    if [ -d "$extracted_dir/devcrew-workspace" ]; then
        # Copy docs from archive (always overwrite)
        if [ -d "$extracted_dir/devcrew-workspace/docs" ]; then
            mkdir -p "$TARGET_DIR/devcrew-workspace/docs"
            for doc in "$extracted_dir/devcrew-workspace/docs"/*.md; do
                if [ -f "$doc" ]; then
                    doc_name=$(basename "$doc")
                    if [ -f "$TARGET_DIR/devcrew-workspace/docs/$doc_name" ]; then
                        print_info "Updated doc: $doc_name"
                    else
                        print_info "Added new doc: $doc_name"
                    fi
                    cp "$doc" "$TARGET_DIR/devcrew-workspace/docs/"
                fi
            done
        fi
        
        print_success "Updated devcrew-workspace/ directory from archive."
    else
        # Archive doesn't include devcrew-workspace, create minimal structure
        print_warning "devcrew-workspace not found in archive, creating minimal structure"
        
        mkdir -p "$TARGET_DIR/devcrew-workspace/docs"
        
        # Download essential docs from raw URLs (try Gitee first, fallback to GitHub)
        gitee_url="https://gitee.com/amutek/devcrew/raw/main/devcrew-workspace/docs"
        github_url="https://raw.githubusercontent.com/charlesmu99/devcrew/main/devcrew-workspace/docs"
        
        for doc_file in "agent-knowledge-map.md" "leader-agent-definition.md"; do
            doc_target="$TARGET_DIR/devcrew-workspace/docs/$doc_file"
            if [ ! -f "$doc_target" ]; then
                downloaded=false
                
                # Try Gitee first
                if [ "$downloaded" = false ] && command -v curl &> /dev/null; then
                    if curl -fsSL "$gitee_url/$doc_file" -o "$doc_target" --max-time 10 2>/dev/null; then
                        print_info "Downloaded doc: $doc_file (Gitee)"
                        downloaded=true
                    fi
                elif [ "$downloaded" = false ] && command -v wget &> /dev/null; then
                    if wget -q "$gitee_url/$doc_file" -O "$doc_target" --timeout=10 2>/dev/null; then
                        print_info "Downloaded doc: $doc_file (Gitee)"
                        downloaded=true
                    fi
                fi
                
                # Fallback to GitHub
                if [ "$downloaded" = false ] && command -v curl &> /dev/null; then
                    if curl -fsSL "$github_url/$doc_file" -o "$doc_target" --max-time 10 2>/dev/null; then
                        print_info "Downloaded doc: $doc_file (GitHub)"
                        downloaded=true
                    fi
                elif [ "$downloaded" = false ] && command -v wget &> /dev/null; then
                    if wget -q "$github_url/$doc_file" -O "$doc_target" --timeout=10 2>/dev/null; then
                        print_info "Downloaded doc: $doc_file (GitHub)"
                        downloaded=true
                    fi
                fi
                
                if [ "$downloaded" = false ]; then
                    print_warning "Could not download $doc_file from any mirror"
                fi
            fi
        done
        
        print_success "Created minimal devcrew-workspace/ structure."
    fi
    
    # Create knowledge and projects directories if not exist
    mkdir -p "$TARGET_DIR/devcrew-workspace/knowledge"
    mkdir -p "$TARGET_DIR/devcrew-workspace/projects"
    
    # Copy README and LICENSE files to devcrew-workspace/docs for reference (always overwrite)
    local docs_target="$TARGET_DIR/devcrew-workspace/docs"
    for readme in "$extracted_dir"/README*.md; do
        if [ -f "$readme" ]; then
            readme_name=$(basename "$readme")
            if [ -f "$docs_target/$readme_name" ]; then
                print_info "Updated doc: $readme_name"
            else
                print_info "Added doc: $readme_name"
            fi
            cp "$readme" "$docs_target/"
        fi
    done
    # Copy LICENSE file
    if [ -f "$extracted_dir/LICENSE" ]; then
        if [ -f "$docs_target/LICENSE" ]; then
            print_info "Updated doc: LICENSE"
        else
            print_info "Added doc: LICENSE"
        fi
        cp "$extracted_dir/LICENSE" "$docs_target/"
    fi
}

# Verify installation
verify_installation() {
    print_info "Verifying installation..."
    
    local errors=0
    
    if [ ! -d "$TARGET_DIR/.qoder" ]; then
        print_error ".qoder/ directory not found after installation."
        errors=$((errors + 1))
    fi
    
    if [ ! -d "$TARGET_DIR/devcrew-workspace" ]; then
        print_error "devcrew-workspace/ directory not found after installation."
        errors=$((errors + 1))
    fi
    
    if [ $errors -eq 0 ]; then
        print_success "Installation verified successfully!"
        return 0
    else
        return 1
    fi
}

# Print next steps
print_next_steps() {
    echo ""
    echo "========================================"
    print_success "DevCrew has been successfully installed!"
    echo "========================================"
    echo ""
    echo "Next steps:"
    echo ""
    echo "  1. Open your project in Qoder IDE"
    echo "  2. Run the initialization Skill:"
    echo "     'Run devcrew-knowledge-dispatch Skill to initialize the knowledge base'"
    echo ""
    echo "  3. Start using DevCrew with your first requirement!"
    echo ""
    echo "Documentation:"
    echo "  - Agent Knowledge Map: devcrew-workspace/docs/agent-knowledge-map.md"
    echo "  - Project Introduction: README.md"
    echo ""
    echo "To uninstall:"
    echo "  rm -rf .qoder devcrew-workspace"
    echo ""
}

# Main function
main() {
    echo "========================================"
    echo "  DevCrew Installer for Qoder"
    echo "========================================"
    echo ""
    
    # Check OS
    case "$(uname -s)" in
        Darwin*)    print_info "Detected: macOS" ;;
        Linux*)     print_info "Detected: Linux" ;;
        CYGWIN*|MINGW*|MSYS*) 
            print_error "Windows detected. Please use install.ps1 for Windows."
            read -n 1 -s -r -p "Press any key to continue..."
            echo ""
            exit 1
            ;;
        *)          print_warning "Unknown OS: $(uname -s)" ;;
    esac
    
    local exit_code=0
    
    check_qoder_compatibility
    download_devcrew || exit_code=1
    
    if [ $exit_code -eq 0 ]; then
        install_devcrew || exit_code=1
    fi
    
    if [ $exit_code -eq 0 ]; then
        verify_installation || exit_code=1
    fi
    
    if [ $exit_code -eq 0 ]; then
        print_next_steps
    fi
    
    # Pause to keep terminal open
    echo ""
    read -n 1 -s -r -p "Press any key to continue..."
    echo ""
    
    exit $exit_code
}

# Run main function
main "$@"
