# DevCrew Installer Script for Windows
#
# Install from GitHub (Global):
#   Invoke-Expression (Invoke-WebRequest -Uri "https://raw.githubusercontent.com/charlesmu99/devcrew/main/install.ps1").Content
#
# Install from Gitee (China):
#   Invoke-Expression (Invoke-WebRequest -Uri "https://gitee.com/amutek/devcrew/raw/main/install.ps1").Content
#
# Uninstall:
#   .\install.ps1 -Uninstall

param(
    [string]$TargetDir = ".",
    [string]$Mirror = "github",  # Options: github, gitee
    [switch]$Uninstall = $false
)

$ErrorActionPreference = "Stop"

# Configuration - Select mirror
if ($Mirror -eq "gitee") {
    # Try alternative Gitee API endpoint
    $RepoUrl = "https://gitee.com/amutek/devcrew/archive/main.zip"
} else {
    $RepoUrl = "https://github.com/charlesmu99/devcrew/archive/refs/heads/main.zip"
}

$TempDir = [System.IO.Path]::GetTempPath() + [System.Guid]::NewGuid().ToString()

# Colors for output
function Write-Info($message) {
    Write-Host "[INFO] $message" -ForegroundColor Cyan
}

function Write-Success($message) {
    Write-Host "[SUCCESS] $message" -ForegroundColor Green
}

function Write-Warning($message) {
    Write-Host "[WARNING] $message" -ForegroundColor Yellow
}

function Write-Error($message) {
    Write-Host "[ERROR] $message" -ForegroundColor Red
}

# Cleanup function
function Cleanup {
    if (Test-Path $TempDir) {
        Remove-Item -Recurse -Force $TempDir -ErrorAction SilentlyContinue
    }
}

# Uninstall DevCrew
function Uninstall-DevCrew {
    Write-Host "========================================" -ForegroundColor Yellow
    Write-Host "  DevCrew Uninstaller" -ForegroundColor Yellow
    Write-Host "========================================" -ForegroundColor Yellow
    Write-Host ""
    
    Write-Warning "This will remove all DevCrew-related files while preserving your custom agents and skills."
    $response = Read-Host "Do you want to proceed with uninstallation? (y/N)"
    if ($response -notmatch '^[Yy]$') {
        Write-Info "Uninstallation cancelled."
        return
    }
    
    Write-Info "Uninstalling DevCrew..."
    
    # Remove devcrew-prefixed agents
    $agentsPath = Join-Path $TargetDir ".qoder\agents"
    if (Test-Path $agentsPath) {
        $devcrewAgents = Get-ChildItem -Path $agentsPath -Filter "devcrew-*.md" -ErrorAction SilentlyContinue
        foreach ($agent in $devcrewAgents) {
            Remove-Item -Path $agent.FullName -Force
            Write-Info "Removed agent: $($agent.Name)"
        }
    }
    
    # Remove devcrew-prefixed skills
    $skillsPath = Join-Path $TargetDir ".qoder\skills"
    if (Test-Path $skillsPath) {
        $devcrewSkills = Get-ChildItem -Path $skillsPath -Directory -Filter "devcrew-*" -ErrorAction SilentlyContinue
        foreach ($skill in $devcrewSkills) {
            Remove-Item -Recurse -Force $skill.FullName
            Write-Info "Removed skill: $($skill.Name)"
        }
    }
    
    # Remove devcrew-workspace directory
    $workspacePath = Join-Path $TargetDir "devcrew-workspace"
    if (Test-Path $workspacePath) {
        Remove-Item -Recurse -Force $workspacePath
        Write-Info "Removed directory: devcrew-workspace/"
    }
    
    Write-Host ""
    Write-Success "DevCrew has been successfully uninstalled!"
    Write-Host ""
    Write-Host "Note: Your custom agents and skills in .qoder/ have been preserved." -ForegroundColor Cyan
    Write-Host "To completely remove all Qoder configurations, manually delete the .qoder/ directory." -ForegroundColor Cyan
}

# Check if DevCrew is already installed
# Note: .qoder directory is auto-generated by Qoder IDE, so we check for devcrew-specific content
function Check-QoderCompatibility {
    Write-Info "Checking Qoder compatibility..."
    
    $devcrewInstalled = $false
    $agentsPath = Join-Path $TargetDir ".qoder\agents"
    $skillsPath = Join-Path $TargetDir ".qoder\skills"
    $workspacePath = Join-Path $TargetDir "devcrew-workspace"
    
    # Check for devcrew-prefixed agents
    if (Test-Path $agentsPath) {
        $devcrewAgents = Get-ChildItem -Path $agentsPath -Filter "devcrew-*.md" -ErrorAction SilentlyContinue
        if ($devcrewAgents) {
            $devcrewInstalled = $true
        }
    }
    
    # Check for devcrew-prefixed skills
    if (Test-Path $skillsPath) {
        $devcrewSkills = Get-ChildItem -Path $skillsPath -Directory -Filter "devcrew-*" -ErrorAction SilentlyContinue
        if ($devcrewSkills) {
            $devcrewInstalled = $true
        }
    }
    
    # Check for devcrew-workspace
    if (Test-Path $workspacePath) {
        $devcrewInstalled = $true
    }
    
    if ($devcrewInstalled) {
        Write-Warning "DevCrew appears to be already installed in this directory."
        Write-Host ""
        $response = Read-Host "Do you want to update the existing installation? (y/N)"
        if ($response -notmatch '^[Yy]$') {
            Write-Info "Installation cancelled."
            exit 0
        }
        Write-Info "Proceeding with update..."
    }
}

# Download DevCrew
function Download-DevCrew {
    Write-Info "Downloading DevCrew..."
    
    $zipPath = Join-Path $TempDir "devcrew.zip"
    
    try {
        Invoke-WebRequest -Uri $RepoUrl -OutFile $zipPath -UseBasicParsing
        Write-Success "Download completed."
    }
    catch {
        Write-Error "Failed to download DevCrew. Please check your internet connection."
        exit 1
    }
    
    return $zipPath
}

# Extract and install
function Install-DevCrew($zipPath) {
    Write-Info "Extracting files..."
    
    Expand-Archive -Path $zipPath -DestinationPath $TempDir -Force
    
    $extractedDir = Get-ChildItem -Path $TempDir -Directory | Where-Object { $_.Name -like "devcrew*" } | Select-Object -First 1
    
    if (-not $extractedDir) {
        Write-Error "Could not find extracted DevCrew directory."
        exit 1
    }
    
    Write-Info "Installing DevCrew to $TargetDir..."
    
    # Create target directory if it doesn't exist
    if (-not (Test-Path $TargetDir)) {
        New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
    }
    
    # Copy .qoder directory (incremental update)
    $qoderSource = Join-Path $extractedDir.FullName ".qoder"
    if (Test-Path $qoderSource) {
        $qoderTarget = Join-Path $TargetDir ".qoder"
        New-Item -ItemType Directory -Path $qoderTarget -Force | Out-Null
        
        # Copy agents (overwrite devcrew- prefixed, skip others)
        $agentsSource = Join-Path $qoderSource "agents"
        if (Test-Path $agentsSource) {
            $agentsTarget = Join-Path $qoderTarget "agents"
            New-Item -ItemType Directory -Path $agentsTarget -Force | Out-Null
            Get-ChildItem -Path $agentsSource -Filter "*.md" | ForEach-Object {
                $agentTarget = Join-Path $agentsTarget $_.Name
                $isDevcrew = $_.Name -match '^devcrew-'
                $exists = Test-Path $agentTarget
                if ($isDevcrew -or -not $exists) {
                    Copy-Item -Path $_.FullName -Destination $agentTarget -Force
                    if ($exists) {
                        Write-Info "Updated agent: $($_.Name)"
                    } else {
                        Write-Info "Added new agent: $($_.Name)"
                    }
                }
            }
        }
        
        # Copy skills (overwrite devcrew- prefixed, skip others)
        $skillsSource = Join-Path $qoderSource "skills"
        if (Test-Path $skillsSource) {
            $skillsTarget = Join-Path $qoderTarget "skills"
            New-Item -ItemType Directory -Path $skillsTarget -Force | Out-Null
            Get-ChildItem -Path $skillsSource -Directory | ForEach-Object {
                $skillTarget = Join-Path $skillsTarget $_.Name
                $isDevcrew = $_.Name -match '^devcrew-'
                $exists = Test-Path $skillTarget
                if ($isDevcrew -or -not $exists) {
                    if ($exists) {
                        Remove-Item -Recurse -Force $skillTarget
                        Write-Info "Updated skill: $($_.Name)"
                    } else {
                        Write-Info "Added new skill: $($_.Name)"
                    }
                    Copy-Item -Recurse -Path $_.FullName -Destination $skillTarget
                }
            }
        }
        
        Write-Success "Updated .qoder/ directory (incremental)."
    }
    
    # Copy devcrew-workspace directory (incremental update)
    $workspaceSource = Join-Path $extractedDir.FullName "devcrew-workspace"
    $workspaceTarget = Join-Path $TargetDir "devcrew-workspace"
    New-Item -ItemType Directory -Path $workspaceTarget -Force | Out-Null
    
    if (Test-Path $workspaceSource) {
        # Copy docs from archive (always overwrite)
        $docsSource = Join-Path $workspaceSource "docs"
        if (Test-Path $docsSource) {
            $docsTarget = Join-Path $workspaceTarget "docs"
            New-Item -ItemType Directory -Path $docsTarget -Force | Out-Null
            Get-ChildItem -Path $docsSource -Filter "*.md" | ForEach-Object {
                $docTarget = Join-Path $docsTarget $_.Name
                $exists = Test-Path $docTarget
                Copy-Item -Path $_.FullName -Destination $docTarget -Force
                if ($exists) {
                    Write-Info "Updated doc: $($_.Name)"
                } else {
                    Write-Info "Added new doc: $($_.Name)"
                }
            }
        }
        
        Write-Success "Updated devcrew-workspace/ directory from archive."
    } else {
        Write-Warning "devcrew-workspace source directory not found in archive, creating minimal structure"
        
        # Create minimal docs directory with essential files from raw URLs
        $docsTarget = Join-Path $workspaceTarget "docs"
        New-Item -ItemType Directory -Path $docsTarget -Force | Out-Null
        
        # Download essential doc files from raw URLs
        # Try Gitee first, fallback to GitHub
        $docFiles = @("agent-knowledge-map.md", "leader-agent-definition.md")
        $mirrorUrls = @(
            "https://gitee.com/amutek/devcrew/raw/main/devcrew-workspace/docs",
            "https://raw.githubusercontent.com/charlesmu99/devcrew/main/devcrew-workspace/docs"
        )
        
        foreach ($docFile in $docFiles) {
            $docTargetPath = Join-Path $docsTarget $docFile
            if (-not (Test-Path $docTargetPath)) {
                $downloaded = $false
                foreach ($baseUrl in $mirrorUrls) {
                    $docUrl = "$baseUrl/$docFile"
                    try {
                        Invoke-WebRequest -Uri $docUrl -OutFile $docTargetPath -UseBasicParsing -TimeoutSec 10
                        if (Test-Path $docTargetPath) {
                            Write-Info "Downloaded doc: $docFile"
                            $downloaded = $true
                            break
                        }
                    }
                    catch {
                        # Try next mirror
                    }
                }
                if (-not $downloaded) {
                    Write-Warning "Could not download $docFile from any mirror"
                }
            }
        }
        
        Write-Success "Created minimal devcrew-workspace/ structure."
    }
    
    # Create knowledge and projects directories if not exist
    $knowledgePath = Join-Path $workspaceTarget "knowledge"
    $projectsPath = Join-Path $workspaceTarget "projects"
    New-Item -ItemType Directory -Path $knowledgePath -Force | Out-Null
    New-Item -ItemType Directory -Path $projectsPath -Force | Out-Null
    
    # Copy README and LICENSE files to devcrew-workspace/docs for reference (always overwrite)
    $docsTarget = Join-Path $workspaceTarget "docs"
    Get-ChildItem -Path $extractedDir.FullName -Filter "README*.md" | ForEach-Object {
        $docTargetPath = Join-Path $docsTarget $_.Name
        $exists = Test-Path $docTargetPath
        Copy-Item -Path $_.FullName -Destination $docTargetPath -Force
        if ($exists) {
            Write-Info "Updated doc: $($_.Name)"
        } else {
            Write-Info "Added doc: $($_.Name)"
        }
    }
    # Copy LICENSE file
    $licenseSource = Join-Path $extractedDir.FullName "LICENSE"
    $licenseTarget = Join-Path $docsTarget "LICENSE"
    if (Test-Path $licenseSource) {
        $exists = Test-Path $licenseTarget
        Copy-Item -Path $licenseSource -Destination $licenseTarget -Force
        if ($exists) {
            Write-Info "Updated doc: LICENSE"
        } else {
            Write-Info "Added doc: LICENSE"
        }
    }
}

# Verify installation
function Verify-Installation {
    Write-Info "Verifying installation..."
    
    $errors = 0
    
    $qoderPath = Join-Path $TargetDir ".qoder"
    $workspacePath = Join-Path $TargetDir "devcrew-workspace"
    
    if (-not (Test-Path $qoderPath)) {
        Write-Error ".qoder/ directory not found after installation."
        $errors++
    }
    
    if (-not (Test-Path $workspacePath)) {
        Write-Error "devcrew-workspace/ directory not found after installation."
        $errors++
    }
    
    if ($errors -eq 0) {
        Write-Success "Installation verified successfully!"
        return $true
    }
    else {
        return $false
    }
}

# Print next steps
function Print-NextSteps {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Success "DevCrew has been successfully installed!"
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:"
    Write-Host ""
    Write-Host "  1. Open your project in Qoder IDE"
    Write-Host ""
    Write-Host "  2. Start a new chat dialog and invoke the Leader Agent:"
    Write-Host "     - Type: /devcrew-leader"
    Write-Host "     - Then type: 'Analyze this project' or similar request"
    Write-Host ""
    Write-Host "  3. The Leader Agent will guide you through:"
    Write-Host "     - Project diagnosis and tech stack analysis"
    Write-Host "     - AI engineering infrastructure setup"
    Write-Host "     - Knowledge base initialization"
    Write-Host ""
    Write-Host "Documentation:"
    Write-Host "  - Agent Knowledge Map: devcrew-workspace/docs/agent-knowledge-map.md"
    Write-Host "  - Project Introduction: README.md"
    Write-Host ""
    Write-Host "To uninstall:"
    Write-Host "  Run: .\install.ps1 -Uninstall"
    Write-Host "  Or manually remove: devcrew-workspace/ and devcrew-* files in .qoder/"
    Write-Host ""
}

# Main function
function Main {
    # Check if uninstall mode
    if ($Uninstall) {
        Uninstall-DevCrew
        
        # Pause to keep window open
        Write-Host ""
        Write-Host "Press any key to continue..." -ForegroundColor Cyan
        $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
        return
    }
    
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "  DevCrew Installer for Qoder" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
    
    # Check OS
    $os = [System.Environment]::OSVersion.Platform
    Write-Info "Detected: Windows"
    
    # Create temp directory
    New-Item -ItemType Directory -Path $TempDir -Force | Out-Null
    
    $success = $false
    try {
        Check-QoderCompatibility
        $zipPath = Download-DevCrew
        Install-DevCrew $zipPath
        
        if (Verify-Installation) {
            Print-NextSteps
            $success = $true
        }
        else {
            Write-Error "Installation verification failed."
        }
    }
    catch {
        Write-Error "An error occurred during installation: $_"
    }
    finally {
        Cleanup
    }
    
    # Pause to keep window open
    Write-Host ""
    Write-Host "Press any key to continue..." -ForegroundColor Cyan
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    
    if (-not $success) {
        exit 1
    }
}

# Run main function
Main
